version: '3.8'
services:
  db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 1s
      interval: 1s
      timeout: 5s
      retries: 55
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
